### ISSUE TITLE
404 on https://nucleo.neatocloud.com/vendors/neato/robots/XXXXXXX/messages

### ISSUE THREAD

**Issue by qelanhari** [kangguru/botvac#2]
Hi, 

I just tried your API (well, the python version)
Byt, I got 404 on all calls. Did they change the API routes ? I noticed they released a new App to support D3 and D5 robots, maybe its related ?

**Comment by tomrosenback** [comment]
Just tested and everything works as it should, are you sure you have tested everything correctly?

**Comment by qelanhari** [comment]
API reponds 404 with something like "No robot found with serial for given vendor" (I dont have the exact message right now, i am on my phone).
I have double and tripled checked my robot serial in the url.
I tried manually (with certs and auth ect...) and with the lib.

**Comment by kangguru** [comment]
hmm, for me it sometimes happened that the secret changed for some reason ... and if i remember correctly it revealed a message similar to what you're seeing.

did you already try to fetch the robots again? does the secret match?

**Comment by qelanhari** [comment]
Well, I should have looked at this before. Secret did change.
All is fine, I can close this issue. 
Thanks for your inputs :)

**Comment by kangguru** [comment]
👯  i like those most! happy cleaning! :)

**Comment by qelanhari** [comment]
Thanks. I'm gonna create a docker image that syncs my google calendar to adjust cleaning hours depending on working hours :)
